CREATE TABLE askreddit25 (
    data_after VARCHAR(9) CHARACTER SET utf8,
    data_before INT,
    data_children_list INT,
    data_children_list_data_approved_by INT,
    data_children_list_data_archived VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_author VARCHAR(18) CHARACTER SET utf8,
    data_children_list_data_author_flair_css_class INT,
    data_children_list_data_author_flair_text INT,
    data_children_list_data_banned_by INT,
    data_children_list_data_clicked VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_created NUMERIC(11, 1),
    data_children_list_data_created_utc NUMERIC(11, 1),
    data_children_list_data_distinguished VARCHAR(9) CHARACTER SET utf8,
    data_children_list_data_domain VARCHAR(14) CHARACTER SET utf8,
    data_children_list_data_downs INT,
    data_children_list_data_edited VARCHAR(12) CHARACTER SET utf8,
    data_children_list_data_from INT,
    data_children_list_data_from_id INT,
    data_children_list_data_from_kind INT,
    data_children_list_data_gilded INT,
    data_children_list_data_hidden VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_hide_score VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_id VARCHAR(6) CHARACTER SET utf8,
    data_children_list_data_is_self VARCHAR(4) CHARACTER SET utf8,
    data_children_list_data_likes INT,
    data_children_list_data_link_flair_css_class VARCHAR(8) CHARACTER SET utf8,
    data_children_list_data_link_flair_text VARCHAR(7) CHARACTER SET utf8,
    data_children_list_data_locked VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_media INT,
    data_children_list_data_name VARCHAR(9) CHARACTER SET utf8,
    data_children_list_data_num_comments INT,
    data_children_list_data_num_reports INT,
    data_children_list_data_over_18 VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_permalink VARCHAR(79) CHARACTER SET utf8,
    data_children_list_data_quarantine VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_removal_reason INT,
    data_children_list_data_report_reasons INT,
    data_children_list_data_saved VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_score INT,
    data_children_list_data_secure_media INT,
    data_children_list_data_selftext VARCHAR(1609) CHARACTER SET utf8,
    data_children_list_data_selftext_html VARCHAR(2042) CHARACTER SET utf8,
    data_children_list_data_stickied VARCHAR(5) CHARACTER SET utf8,
    data_children_list_data_subreddit VARCHAR(9) CHARACTER SET utf8,
    data_children_list_data_subreddit_id VARCHAR(8) CHARACTER SET utf8,
    data_children_list_data_suggested_sort INT,
    data_children_list_data_thumbnail INT,
    data_children_list_data_title VARCHAR(129) CHARACTER SET utf8,
    data_children_list_data_ups INT,
    data_children_list_data_url VARCHAR(101) CHARACTER SET utf8,
    data_children_list_data_visited VARCHAR(5) CHARACTER SET utf8,
    data_children_list_kind VARCHAR(2) CHARACTER SET utf8,
    data_modhash INT,
    kind VARCHAR(7) CHARACTER SET utf8
);
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','UnholyDemigod',NULL,NULL,NULL,'False',1460714287.0,1460685487.0,'moderator','self.AskReddit',0,'1460685963.0',NULL,NULL,NULL,0,'False','True','4eujyq','True',NULL,'mod-post','Modpost','False',NULL,'t3_4eujyq',66,NULL,'False','/r/AskReddit/comments/4eujyq/raskreddits_originality_contest_round_2/','False',NULL,NULL,'False',62,NULL,'Hey readers! You may remember that some time ago we had a [little contest](https://www.reddit.com/r/AskReddit/comments/2z2lu1/announcing_a_small_contest_to_promote_originality/) for the most original question. Well it was pretty popular at the time, so we''re going to follow our own trend of originality and hold the exact same contest again. The rules for the contest are as follows:

* the question deemed most original *and* discussion inspiring as voted *by the mods* will receive reddit gold and a night with the supermodel of your choice (provided you seek her/him out of your own accord and they agree to your advances)

* ''Sexiest sex you ever sexed'' or any other NSFW threads do not qualify. We want originality, not something you can jerk off to. 

* threads do not have to be marked as serious to be considered. 

* post must be within all the rules of the sub (duh)

* most importantly: this is not forced entry. If you do not wish to wrack your brain thinking of something new, feel free to ask any of the other generic questions that pop up every day. 

Apart from that, all you have to do is think of a question to post. We will do all the work of saving links and voting on them and whatnot, so you can browse and read the same way you always do. The contest will last for a fortnight from today (this thread will be stickied the whole time), after which we go to our secret hideout on Skull Island and decide which we think is the winner (or winners, if we can''t choose). 

EDIT: disclaimer that is apparently required - do not post your questions in here. Post them as you normally would. 

','<!-- SC_OFF --><div class="md"><p>Hey readers! You may remember that some time ago we had a <a href="https://www.reddit.com/r/AskReddit/comments/2z2lu1/announcing_a_small_contest_to_promote_originality/">little contest</a> for the most original question. Well it was pretty popular at the time, so we&#39;re going to follow our own trend of originality and hold the exact same contest again. The rules for the contest are as follows:</p>

<ul>
<li><p>the question deemed most original <em>and</em> discussion inspiring as voted <em>by the mods</em> will receive reddit gold and a night with the supermodel of your choice (provided you seek her/him out of your own accord and they agree to your advances)</p></li>
<li><p>&#39;Sexiest sex you ever sexed&#39; or any other NSFW threads do not qualify. We want originality, not something you can jerk off to. </p></li>
<li><p>threads do not have to be marked as serious to be considered. </p></li>
<li><p>post must be within all the rules of the sub (duh)</p></li>
<li><p>most importantly: this is not forced entry. If you do not wish to wrack your brain thinking of something new, feel free to ask any of the other generic questions that pop up every day. </p></li>
</ul>

<p>Apart from that, all you have to do is think of a question to post. We will do all the work of saving links and voting on them and whatnot, so you can browse and read the same way you always do. The contest will last for a fortnight from today (this thread will be stickied the whole time), after which we go to our secret hideout on Skull Island and decide which we think is the winner (or winners, if we can&#39;t choose). </p>

<p>EDIT: disclaimer that is apparently required - do not post your questions in here. Post them as you normally would. </p>
</div><!-- SC_ON -->','True','AskReddit','t5_2qh1i',NULL,NULL,'/r/askreddit''s originality contest, round 2',62,'https://www.reddit.com/r/AskReddit/comments/4eujyq/raskreddits_originality_contest_round_2/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','seir0',NULL,NULL,NULL,'False',1460683710.0,1460654910.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4es91w','True',NULL,NULL,NULL,'False',NULL,'t3_4es91w',1515,NULL,'False','/r/AskReddit/comments/4es91w/if_there_was_a_reddit_gold_counterpart_called/','False',NULL,NULL,'False',3727,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'If there was a "Reddit Gold" counterpart called "Reddit Shit" to give to annoying Redditors, what features would make you buy it?',3727,'https://www.reddit.com/r/AskReddit/comments/4es91w/if_there_was_a_reddit_gold_counterpart_called/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Generalkrunk',NULL,NULL,NULL,'False',1460660770.0,1460631970.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eqmpd','True',NULL,NULL,NULL,'False',NULL,'t3_4eqmpd',19239,NULL,'False','/r/AskReddit/comments/4eqmpd/what_is_your_hidden_useless_talent/','False',NULL,NULL,'False',4608,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What is your hidden, useless, talent?',4608,'https://www.reddit.com/r/AskReddit/comments/4eqmpd/what_is_your_hidden_useless_talent/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','K4S3R',NULL,NULL,NULL,'False',1460703346.0,1460674546.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4ettdt','True',NULL,NULL,NULL,'False',NULL,'t3_4ettdt',617,NULL,'False','/r/AskReddit/comments/4ettdt/what_is_the_most_terrifying_single_line_youve/','False',NULL,NULL,'False',476,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What is the most terrifying single line you''ve ever heard a character say in a movie or TV show?',476,'https://www.reddit.com/r/AskReddit/comments/4ettdt/what_is_the_most_terrifying_single_line_youve/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Bruce_Lee_Roy',NULL,NULL,NULL,'False',1460661266.0,1460632466.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eqnj3','True',NULL,NULL,NULL,'False',NULL,'t3_4eqnj3',8278,NULL,'False','/r/AskReddit/comments/4eqnj3/what_is_something_that_is_not_illegal_that_the/','False',NULL,NULL,'False',3495,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What is something that is NOT illegal, that "the worse kind of person" does?',3495,'https://www.reddit.com/r/AskReddit/comments/4eqnj3/what_is_something_that_is_not_illegal_that_the/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','ForeverAbyss',NULL,NULL,NULL,'False',1460667834.0,1460639034.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4er0pi','True',NULL,NULL,NULL,'False',NULL,'t3_4er0pi',4482,NULL,'False','/r/AskReddit/comments/4er0pi/whats_a_mind_blowing_fact/','False',NULL,NULL,'False',2022,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What''s a mind blowing fact?',2022,'https://www.reddit.com/r/AskReddit/comments/4er0pi/whats_a_mind_blowing_fact/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','TheManWithNoName88',NULL,NULL,NULL,'False',1460670340.0,1460641540.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4er6rx','True',NULL,NULL,NULL,'False',NULL,'t3_4er6rx',1800,NULL,'False','/r/AskReddit/comments/4er6rx/shy_men_of_reddit_how_did_you_meet_your/','False',NULL,NULL,'False',1739,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Shy men of reddit, how did you meet your girlfriend/SO?',1739,'https://www.reddit.com/r/AskReddit/comments/4er6rx/shy_men_of_reddit_how_did_you_meet_your/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Jimbobsupertramp',NULL,NULL,NULL,'False',1460680143.0,1460651343.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4erybc','True',NULL,NULL,NULL,'False',NULL,'t3_4erybc',1069,NULL,'False','/r/AskReddit/comments/4erybc/what_is_something_anything_that_not_a_lot_of/','False',NULL,NULL,'False',727,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What is something (anything) that not a lot of people know is in the works right now, and will be huge once it is completed?',727,'https://www.reddit.com/r/AskReddit/comments/4erybc/what_is_something_anything_that_not_a_lot_of/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','elmostaco',NULL,NULL,NULL,'False',1460704799.0,1460675999.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4etx46','True',NULL,NULL,NULL,'False',NULL,'t3_4etx46',48,NULL,'False','/r/AskReddit/comments/4etx46/psychologists_of_reddit_how_has_your_own_personal/','False',NULL,NULL,'False',162,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Psychologists of Reddit: how has your own personal perception of everyday people changed throughout your career?',162,'https://www.reddit.com/r/AskReddit/comments/4etx46/psychologists_of_reddit_how_has_your_own_personal/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','skyliner360',NULL,NULL,NULL,'False',1460674835.0,1460646035.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4erj2e','True',NULL,NULL,NULL,'False',NULL,'t3_4erj2e',1536,NULL,'False','/r/AskReddit/comments/4erj2e/whats_a_classic_dick_move/','False',NULL,NULL,'False',720,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What''s a classic "dick move?"',720,'https://www.reddit.com/r/AskReddit/comments/4erj2e/whats_a_classic_dick_move/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','MrChinchilla',NULL,NULL,NULL,'False',1460689349.0,1460660549.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4espt3','True',NULL,NULL,NULL,'False',NULL,'t3_4espt3',564,NULL,'False','/r/AskReddit/comments/4espt3/you_discover_a_genie_that_only_grants_mediocre/','False',NULL,NULL,'False',343,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'You discover a genie that only grants mediocre wishes. What do you ask for?',343,'https://www.reddit.com/r/AskReddit/comments/4espt3/you_discover_a_genie_that_only_grants_mediocre/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','psyciked',NULL,NULL,NULL,'False',1460677418.0,1460648618.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4erqck','True',NULL,NULL,NULL,'False',NULL,'t3_4erqck',544,NULL,'False','/r/AskReddit/comments/4erqck/redditors_who_have_won_a_contest_to_spend_a_day/','False',NULL,NULL,'False',594,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Redditors who have won a contest to "spend a day with a celebrity," what was it like?',594,'https://www.reddit.com/r/AskReddit/comments/4erqck/redditors_who_have_won_a_contest_to_spend_a_day/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Hitsuba',NULL,NULL,NULL,'False',1460708363.0,1460679563.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eu5vo','True',NULL,NULL,NULL,'False',NULL,'t3_4eu5vo',307,NULL,'False','/r/AskReddit/comments/4eu5vo/what_did_high_school_teach_you/','False',NULL,NULL,'False',120,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What did high school teach you?',120,'https://www.reddit.com/r/AskReddit/comments/4eu5vo/what_did_high_school_teach_you/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','AmericanDerp',NULL,NULL,NULL,'False',1460694721.0,1460665921.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4et5p7','True',NULL,NULL,NULL,'False',NULL,'t3_4et5p7',280,NULL,'False','/r/AskReddit/comments/4et5p7/which_childrens_television_fictional_universes/','False',NULL,NULL,'False',201,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Which children''s television fictional universes would be most terrifying to find yourself trapped in?',201,'https://www.reddit.com/r/AskReddit/comments/4et5p7/which_childrens_television_fictional_universes/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','TriIIuminati',NULL,NULL,NULL,'False',1460691076.0,1460662276.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4esuzh','True',NULL,NULL,NULL,'False',NULL,'t3_4esuzh',394,NULL,'False','/r/AskReddit/comments/4esuzh/redditors_who_have_successfully_evadedran_from/','False',NULL,NULL,'False',208,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Redditors who have successfully evaded/ran from the cops, how did you do it?',208,'https://www.reddit.com/r/AskReddit/comments/4esuzh/redditors_who_have_successfully_evadedran_from/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','bertonomus',NULL,NULL,NULL,'False',1460663798.0,1460634998.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eqs6b','True',NULL,NULL,NULL,'False',NULL,'t3_4eqs6b',2456,NULL,'False','/r/AskReddit/comments/4eqs6b/in_your_opinion_what_should_reddit_shut_up_about/','False',NULL,NULL,'False',777,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'In your opinion, what should Reddit shut up about?',777,'https://www.reddit.com/r/AskReddit/comments/4eqs6b/in_your_opinion_what_should_reddit_shut_up_about/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','FrickOffRandy',NULL,NULL,NULL,'False',1460700961.0,1460672161.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4etn5v','True',NULL,NULL,NULL,'False',NULL,'t3_4etn5v',205,NULL,'False','/r/AskReddit/comments/4etn5v/what_are_you_doing_behind_your_sos_back_that_isnt/','False',NULL,NULL,'False',107,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What are you doing behind your SO''s back that isn''t major but would cause drama?',107,'https://www.reddit.com/r/AskReddit/comments/4etn5v/what_are_you_doing_behind_your_sos_back_that_isnt/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','KuyaRussell',NULL,NULL,NULL,'False',1460700285.0,1460671485.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4etlc1','True',NULL,NULL,NULL,'False',NULL,'t3_4etlc1',245,NULL,'True','/r/AskReddit/comments/4etlc1/whats_the_worst_would_you_rather_scenario_you_can/','False',NULL,NULL,'False',110,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What''s the worst "would you rather" scenario you can think of?',110,'https://www.reddit.com/r/AskReddit/comments/4etlc1/whats_the_worst_would_you_rather_scenario_you_can/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','toddmygodd',NULL,NULL,NULL,'False',1460704139.0,1460675339.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4etvgt','True',NULL,NULL,NULL,'False',NULL,'t3_4etvgt',70,NULL,'False','/r/AskReddit/comments/4etvgt/teachers_of_reddit_whats_the_weirdest_thing_youve/','False',NULL,NULL,'False',82,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Teachers of Reddit, What''s the weirdest thing you''ve overheard from students?',82,'https://www.reddit.com/r/AskReddit/comments/4etvgt/teachers_of_reddit_whats_the_weirdest_thing_youve/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','HaydnOSmith',NULL,NULL,NULL,'False',1460674556.0,1460645756.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eri5r','True',NULL,NULL,NULL,'False',NULL,'t3_4eri5r',687,NULL,'False','/r/AskReddit/comments/4eri5r/redditors_what_horror_films_involve_a_good_story/','False',NULL,NULL,'False',367,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Redditors, what Horror films involve a good story and a genuine element of fear rather than just jumpscares?',367,'https://www.reddit.com/r/AskReddit/comments/4eri5r/redditors_what_horror_films_involve_a_good_story/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Mandalorianfist',NULL,NULL,NULL,'False',1460669485.0,1460640685.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4er4ng','True',NULL,NULL,NULL,'False',NULL,'t3_4er4ng',1780,NULL,'False','/r/AskReddit/comments/4er4ng/what_commercial_do_you_absolutely_hate_and_why/','False',NULL,NULL,'False',428,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What commercial do you absolutely hate, and why?',428,'https://www.reddit.com/r/AskReddit/comments/4er4ng/what_commercial_do_you_absolutely_hate_and_why/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','caposhitliner',NULL,NULL,NULL,'False',1460710679.0,1460681879.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eubc2','True',NULL,NULL,NULL,'False',NULL,'t3_4eubc2',103,NULL,'False','/r/AskReddit/comments/4eubc2/what_movie_on_netflix_us_is_a_hidden_gem/','False',NULL,NULL,'False',54,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What movie on Netflix (US) is a hidden gem?',54,'https://www.reddit.com/r/AskReddit/comments/4eubc2/what_movie_on_netflix_us_is_a_hidden_gem/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','snappyirides',NULL,NULL,NULL,'False',1460708673.0,1460679873.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eu6kz','True',NULL,NULL,NULL,'False',NULL,'t3_4eu6kz',85,NULL,'False','/r/AskReddit/comments/4eu6kz/what_songs_give_good_life_advice/','False',NULL,NULL,'False',56,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What songs give good life advice?',56,'https://www.reddit.com/r/AskReddit/comments/4eu6kz/what_songs_give_good_life_advice/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','Fuzbaul',NULL,NULL,NULL,'False',1460705319.0,1460676519.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4etyej','True',NULL,NULL,NULL,'False',NULL,'t3_4etyej',206,NULL,'False','/r/AskReddit/comments/4etyej/who_is_that_one_persontype_of_person_you_cannot/','False',NULL,NULL,'False',62,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'Who is that one person/type of person you cannot stand at all?',62,'https://www.reddit.com/r/AskReddit/comments/4etyej/who_is_that_one_persontype_of_person_you_cannot/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES (NULL,NULL,NULL,NULL,'False','GodOfDumbness',NULL,NULL,NULL,'False',1460628975.0,1460600175.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4ep1he','True',NULL,NULL,NULL,'False',NULL,'t3_4ep1he',7706,NULL,'False','/r/AskReddit/comments/4ep1he/what_is_a_video_game_you_still_play_to_this_day/','False',NULL,NULL,'False',3031,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What is a video game you still play to this day despite it being "Dead" or ancient ?',3031,'https://www.reddit.com/r/AskReddit/comments/4ep1he/what_is_a_video_game_you_still_play_to_this_day/','False','t3',NULL,'Listing');
INSERT INTO askreddit25 VALUES ('t3_4eoa1c',NULL,NULL,NULL,'False','TheHoliestMacaroni',NULL,NULL,NULL,'False',1460618113.0,1460589313.0,NULL,'self.AskReddit',0,'False',NULL,NULL,NULL,0,'False','False','4eoa1c','True',NULL,NULL,NULL,'False',NULL,'t3_4eoa1c',8627,NULL,'True','/r/AskReddit/comments/4eoa1c/whats_the_fetish_you_havent_told_your_so_about/','False',NULL,NULL,'False',4341,NULL,NULL,NULL,'False','AskReddit','t5_2qh1i',NULL,NULL,'What''s the fetish you haven''t told your SO about?',4341,'https://www.reddit.com/r/AskReddit/comments/4eoa1c/whats_the_fetish_you_havent_told_your_so_about/','False','t3',NULL,'Listing');
